version: "3.8"
services:
    gsg_apache_server:
        image: "crgbe/php:8.1-apache-bullseye"
        container_name: gsg_apache_server
        ports:
            - "8080:80"
        volumes:
            - "./:/var/www/html"

    gsg_node_server:
        image: "crgbe/node:14.15-alpine"
        container_name: gsg_node_server
        ports:
            -   "9090:8080"
        entrypoint: /usr/local/bin/docker-yarn-entrypoint
        depends_on:
            -   gsg_apache_server
        volumes:
            -   "./:/var/www/html"

    gsg_mysql_server_57:
        image: mysql:5.7
        ports:
            - "9306:3306"
        environment:
            MYSQL_DATABASE: globsavgrp
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - "gsg_mysql-dbdata:/var/lib/mysql"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
    gsg_mysql-dbdata:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
