version: "3.8"
services:
    gsg_apache:
        image: "crgbe/php:8.1-apache-bullseye"
        container_name: gsg_apache
        ports:
            - "8080:80"
        volumes:
            - "./backend:/var/www/html"
            - "./frontend:/var/www/frontend"

    gsg_node:
        image: "crgbe/node:19-alpine"
        container_name: gsg_node
        ports:
            -   "9090:8080"
        entrypoint: /usr/local/bin/docker-yarn-entrypoint
        depends_on:
            -   gsg_apache
        volumes:
            -   "./frontend:/var/www/html"

    mysql_57:
        image: mysql:5.7
        ports:
            - "9306:3306"
        environment:
            MYSQL_DATABASE: gsg
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - "mysql-dbdata:/var/lib/mysql"

volumes:
    mysql-dbdata: