version: "3.8"
services:
    gsg_apache_server:
        image: "crgbe/php:8.1-apache-bullseye"
        container_name: gsg_apache_server
        ports:
            - "8080:80"
        volumes:
            - "./:/var/www/html"

    gsg_node_server:
        image: "crgbe/node:14.15-alpine"
        container_name: gsg_node_server
        ports:
            -   "9090:8080"
        entrypoint: /usr/local/bin/docker-yarn-entrypoint
        depends_on:
            -   gsg_apache_server
        volumes:
            -   "./:/var/www/html"

    gsg_mysql_server_57:
        image: mysql:5.7
        ports:
            - "9306:3306"
        environment:
            MYSQL_DATABASE: globsavgrp
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - "gsg_mysql-dbdata:/var/lib/mysql"

volumes:
    gsg_mysql-dbdata: